//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class asistencia
    {
        public int id { get; set; }
        public short id_Trabajador { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_entrada { get; set; }
        public System.TimeSpan hora_salida { get; set; }
    
        public virtual trabajador trabajador { get; set; }
    }
}
