//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public servicio()
        {
            this.servicio_adicional = new HashSet<servicio_adicional>();
        }
    
        public int id_Servicio { get; set; }
        public short id_Trabajador { get; set; }
        public int id_Vehiculo { get; set; }
        public Nullable<short> id_TarifaL { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public bool estado_pago { get; set; }
        public Nullable<System.DateTime> fecha_pago { get; set; }
        public decimal precioLav { get; set; }
        public decimal descuento { get; set; }
        public Nullable<decimal> preciosAdic { get; set; }
        public bool estado_servicio { get; set; }
        public System.TimeSpan hora_salida { get; set; }
    
        public virtual tarifa_lavado tarifa_lavado { get; set; }
        public virtual trabajador trabajador { get; set; }
        public virtual vehiculo vehiculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servicio_adicional> servicio_adicional { get; set; }
    }
}
