//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio_adicional
    {
        public int id_SA { get; set; }
        public int id_Servicio { get; set; }
        public short id_TA { get; set; }
        public decimal precioAct { get; set; }
    
        public virtual servicio servicio { get; set; }
        public virtual tarifa_adicional tarifa_adicional { get; set; }
    }
}
