//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajador_egreso
    {
        public int id_TE { get; set; }
        public short id_Trabajador { get; set; }
        public string descripcion { get; set; }
        public decimal costo { get; set; }
        public System.DateTime fecha_compra { get; set; }
    
        public virtual trabajador trabajador { get; set; }
    }
}
